### ISSUE TITLE
print attributes?

### ISSUE THREAD

**Issue by axelav** [pthrasher/cli-scrape#1]
is it possible to print attributes using this?

**Comment by pthrasher** [comment]
Yes, you'll have to use xpath for your selector though.

For example, if you wanted to get the text of an attribute of a an a tag: href, you'd do this:
/html/body//a/@href

**Comment by pthrasher** [comment]
@axelav Did my suggestion work for you?

**Comment by axelav** [comment]
Sorry, I was moving over the weekend & haven't had a chance to test this, but I think this will work just fine. I'll just have to familiarize myself with xpath. Thanks!
